### ISSUE TITLE
Building x86 application

### ISSUE THREAD

**Issue by Insid3CodeTeam** [GleeBug/GleeBug#17]
No conditional directive #def for x86/x64 platform support when building x86 application leads to compilation error:
..\MyDebugger.h(75) : error C2039: 'Rip' : is not a member of 'GleeBug::RegistersInfo'
..\MyDebugger.h(81) : error C2039: 'Rip' : is not a member of 'GleeBug::RegistersInfo'

snippet:
----------
void boobs()
	{
		printf("(.)Y(.) 0x%p\n",
			_thread->registers.Rip);
	}

	virtual void cbSystemBreakpoint()
	{
		printf("System breakpoint reached, CIP: 0x%p\n",
			_thread->registers.Rip);
		_thread->StepInto(BIND(this, MyDebugger::boobs));
	}
---------

**Comment by mrexodia** [comment]
You cannot debug x64 applications from x32 as far as I know...
